[alembic]
script_location = %(here)s/migrations
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s
path_separator = os

# Новая миграция сразу проходит линтер и форматтер.
[post_write_hooks]
hooks = ruff_fix, ruff_format
ruff_fix.type = exec
ruff_fix.executable = ruff
ruff_fix.options = check --fix --quiet REVISION_SCRIPT_FILENAME
ruff_format.type = exec
ruff_format.executable = ruff
ruff_format.options = format --quiet REVISION_SCRIPT_FILENAME
