"""Гейт миграций: схема в базе обязана совпадать с моделями, а миграции — откатываться."""

from alembic import command

from tests.conftest import alembic_config


def test_models_match_migrations() -> None:
    # Бросает AutogenerateDiffsDetected, если модель изменили, а миграцию не написали.
    command.check(alembic_config())


def test_migrations_roll_back_and_forward() -> None:
    config = alembic_config()

    command.downgrade(config, "base")
    command.upgrade(config, "head")
    command.check(config)
